name: shushingfairy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92049
title: Shushing Fairy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d3d3d3'
    - '#3e3e3e'
    - '#686868'
  brandStrength: 0.6875
  lightness: 0.20937394630163908
  saturation: 0.9206060469150543
  rhythmicContrast: 0.059040497057139874
purpose: []
