layout_spectrum: 0.37057267378278
typography_spectrum: 0.7958746103008306
color:
  saturation: 0.681037815108545
  brandStrength: 0.8410752313456838
  rhythmicContrast: 0.19370886673145735
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.029300936140249124
title: Shushing Fairy
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac2cf0e8-035a-4c0a-b66c-14df8c49334b.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac2cf0e8-035a-4c0a-b66c-14df8c49334b.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Experimental and Obscure Indie Games for the Insanity of Mind
cta:
  bucket: null
  version: null
  domain: null
name: Shushing Fairy
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
